package events

import (
	"encoding/json"
	"fmt"
	"time"
	"unicode/utf8"

	"github.com/KaioVinicios/pda/internal/domain/ident"
)

const maxMetadataLen = 128

// Envelope wraps an event with its transport metadata (messaging.md §6.1). It
// is only built by Seal, and its fields are private: the type and version always
// come from the event.
type Envelope struct {
	eventID       string
	correlationID string
	causationID   string
	event         Event
}

// Seal builds the envelope that goes to the outbox. eventID is a canonical
// UUID (UUIDv7, generated by the app before the INSERT); correlationID has 1 to
// 128 characters; causationID is optional, up to 128 characters. The event is
// validated even if it was built without its constructor.
func Seal(eventID, correlationID, causationID string, e Event) (Envelope, error) {
	switch {
	case !ident.Valid(eventID):
		return Envelope{}, fmt.Errorf("%w: event id must be a canonical UUID", ErrInvalidEvent)
	case correlationID == "" || utf8.RuneCountInString(correlationID) > maxMetadataLen:
		return Envelope{}, fmt.Errorf("%w: correlation id must have 1 to 128 characters", ErrInvalidEvent)
	case utf8.RuneCountInString(causationID) > maxMetadataLen:
		return Envelope{}, fmt.Errorf("%w: causation id must have at most 128 characters", ErrInvalidEvent)
	case e == nil:
		return Envelope{}, fmt.Errorf("%w: event is required", ErrInvalidEvent)
	}
	if err := e.validate(); err != nil {
		return Envelope{}, err
	}
	return Envelope{eventID: eventID, correlationID: correlationID, causationID: causationID, event: e}, nil
}

func (e Envelope) EventID() string        { return e.eventID }
func (e Envelope) CorrelationID() string  { return e.correlationID }
func (e Envelope) CausationID() string    { return e.causationID }
func (e Envelope) Event() Event           { return e.event }
func (e Envelope) Type() Type             { return e.event.Type() }
func (e Envelope) Version() int           { return e.event.Version() }
func (e Envelope) MessageGroupID() string { return e.event.MessageGroupID() }
func (e Envelope) OccurredAt() time.Time  { return e.event.OccurredAt() }

func (e Envelope) AggregateType() AggregateType {
	t, _ := e.event.Aggregate()
	return t
}

func (e Envelope) AggregateID() string {
	_, id := e.event.Aggregate()
	return id
}

// MarshalJSON emits the envelope of messaging.md §6.1. message_group_id is an
// outbox column, not part of the JSON.
func (e Envelope) MarshalJSON() ([]byte, error) {
	if e.event == nil {
		return nil, fmt.Errorf("%w: envelope not sealed", ErrInvalidEvent)
	}
	aggType, aggID := e.event.Aggregate()
	return json.Marshal(struct {
		EventID       string        `json:"eventId"`
		EventType     Type          `json:"eventType"`
		Version       int           `json:"version"`
		AggregateType AggregateType `json:"aggregateType"`
		AggregateID   string        `json:"aggregateId"`
		CorrelationID string        `json:"correlationId"`
		CausationID   string        `json:"causationId,omitempty"`
		OccurredAt    Time          `json:"occurredAt"`
		Data          Event         `json:"data"`
	}{
		EventID: e.eventID, EventType: e.event.Type(), Version: e.event.Version(),
		AggregateType: aggType, AggregateID: aggID,
		CorrelationID: e.correlationID, CausationID: e.causationID,
		OccurredAt: NewTime(e.event.OccurredAt()), Data: e.event,
	})
}
